### ISSUE TITLE
Register to book time slots on the robots

### ISSUE THREAD

**Issue by pattacini** [vvv-school/vvv17#18]
Dear @vvv-school/vvv17-students 

You should have received another email asking you to join our **robot booking system**.
Please proceed by following the instructions.

Once done, you'll be able to book time slots on the iCub for testing your assignments for real 😉 

You can reach the **booking dashboard** from within our [Wiki](https://github.com/vvv-school/vvv17/wiki).

**Comment by bbrito** [comment]
How should we organize the time? Are we going to create teams?

**Comment by pattacini** [comment]
I can give an answer for my course on kinematics (3rd day), for which I tend to follow this approach:
- There'll be two assignments in the afternoon, whose the second can run on the robot too.
- The assignment is on an individual basis, so I'm going to check first whether the student will get the grade on the simulator and then I'll give him green light to book the robot.

Therefore, no teams for me, but other teachers may decide differently.

**Comment by pattacini** [comment]
For whoever hasn't done this yet: please, do it before tomorrow.

cc @vvv-school/vvv17-students
