### ISSUE TITLE
Assignment on Yarp producer-consumer 

### ISSUE THREAD

**Issue by apaikan** [vvv-school/vvv17#22]
Click and edit and score 5: 
https://classroom.github.com/assignment-invitations/9ff783408efb2a4c3ef7ee53277977a1

**Comment by pattacini** [comment]
🎖 to @EgorLakomkin for being the first to complete the assignment 😄

**Comment by AlexAntn** [comment]
Hello @apaikan ,

We detected that the test script doesn't catch when we don't properly clear the Bottle from the BufferedPort<Bottle> (in the producer side), which might lead to the Bottle growing forever!

**Comment by apaikan** [comment]
@AlexAntn  well seen! Today unfortunately we could not manage to completely go through the tutorial of `yarp::os::BufferedPort` to cover this part. So i kept it simple by copying the output into the input!  We will cover it tomorrow during the assignment. Btw, +1 for the test! 👍
