### ISSUE TITLE
Assignment Codec (YARP IDL)

### ISSUE THREAD

**Issue by apaikan** [vvv-school/vvv17#27]
Click here and score 4: 

https://classroom.github.com/assignment-invitations/d35c935beba89431fecaf9aa87eb51cd

**Comment by pattacini** [comment]
To run the test locally to your machine, do this beforehand:
```sh
$ cd smoke-test
$ chmod +x test.sh
```

We fixed this upstream!

cc @vvv-school/vvv17-students

**Comment by pattacini** [comment]
cc @vvv-school/vvv17-students

**Comment by pattacini** [comment]
Hey @BarisSerhan 

check out the [**Yarp Gradebook**][1]: you just got full mark 🎖 🎉 🍺 😃 

[1]: https://vvv17-yarp.github.io
