### ISSUE TITLE
Folder Sharing between a host and our VM machine using virtualBox

### ISSUE THREAD

**Issue by vtikha** [vvv-school/vvv17#28]
Just a small note to all, 

if you need to share a folder between a host (Windows/Mac) and the distributed Virtual Machine using **Virtual Box**, please follow these simple steps:
```
 - Devices -> Shared Folders -> Shared Folder Settings
 - Click on the Add Folder icon. 
 - Select the Host Folder and give it a Folder Name, 
 - Tick the "Auto Mount" check-box.
```

Now the magical command will fix all permission errors:
```
sudo adduser icub vboxsf
```
Please **log out** and log back in for it to take effect.

**Comment by pattacini** [comment]
cc @vvv-school/vvv17-students

**Comment by vtikha** [comment]
@pattacini this has nothing to do with **ros** 😄 just VM machine folder sharing

**Comment by pattacini** [comment]
I just tried 😊
