### ISSUE TITLE
Missing links to slides

### ISSUE THREAD

**Issue by pattacini** [vvv-school/vvv17#38]
Hi @francesco-romano 

Could you link slides of today's course from within the wiki?
It seems there're some missing references.

**Comment by francesco-romano** [comment]
Assigning @iron76 and @DanielePucci as only the slides on the theoretical part are missing

**Comment by DanielePucci** [comment]
Done :)

**Comment by pattacini** [comment]
@DanielePucci you're pointing to a private repository 😉 
Could you either copy the pdf here under [_material sub-directory_][1] or disclose the repo?

[1]: https://github.com/vvv-school/vvv17/tree/master/material

**Comment by pattacini** [comment]
It turned out that the repo is accessible by @vvv-school/vvv17-students with read permission.
