### ISSUE TITLE
Assignment on WB-Toolbox

### ISSUE THREAD

**Issue by francesco-romano** [vvv-school/vvv17#44]
@vvv-school/vvv17-students 
here is the first assignment with the Simulink library (WB-Toolbox)

https://classroom.github.com/assignment-invitations/a71a32c7075139bd4f0aabe00f408032

**Comment by vicentepedro** [comment]
https://github.com/robotology/codyco-superbuild/issues/141

If you run in some problem with matlab... 

Error pointed out by @traversaro

**Comment by francesco-romano** [comment]
To test the assignment you have to:
- launch `yarpserver` (sometimes some errors occurred on wifi. In this case simply start everything without connection)
- launch gazebo with the clock (`gazebo -slibgazebo_yarp_clock.so`)
- test your controller 😄
