### ISSUE TITLE
Will we have access to the slides of invited speakers?

### ISSUE THREAD

**Issue by bmagyar** [vvv-school/vvv17#48]
Not sure if it is common to share it but just in case...

@vvv-school/vvv17-teachers

**Comment by vicentepedro** [comment]
@bmagyar, the slides of Prof. Danica Kragic are already available [here](http://icub.org/winterschool/slides/2017-IIT-kort.pdf).

**Comment by pattacini** [comment]
@vicentepedro I've just put the link also from within this Wiki. Thanks! 👍

**Comment by bmagyar** [comment]
Great, thanks! I was a bit confused as currently we have the slides in many places :)

**Comment by pattacini** [comment]
@vvv-school/vvv17-students if you find there's a way to improve the wiki, please give your contribution; you should be able to edit it.
