### ISSUE TITLE
issues with opening the VM

### ISSUE THREAD

**Issue by kompky** [vvv-school/vvv17#5]
Hi @vvv-school/vvv17-teachers 

I am trying to open the VM but i get the following errors:

![icubvirtualmachine1](https://cloud.githubusercontent.com/assets/25303346/22333614/529aae70-e3d7-11e6-97a7-3a01f30609fb.png)

![icubvirtualmachine](https://cloud.githubusercontent.com/assets/25303346/22333620/5a61e222-e3d7-11e6-89f9-9cc69fb9b0c7.png)

Best wishes,
Kyveli.

PS. I have windows 8.1 and x64.

**Comment by mbrunettini** [comment]
Hi,
you should follow the (1) on the image above: open your bios, go to the security settings and enable "Intel VT-x", then save and reboot.
Let us know if it works for you.

**Comment by kompky** [comment]
Thank you very much! Problem solved!

**Comment by pattacini** [comment]
Hi @kompky 

Glad that the fix was swift. You should have received the invitation to join the team.
Please check your email.
