### ISSUE TITLE
First Tutorial on vision 

### ISSUE THREAD

**Issue by vtikha** [vvv-school/vvv17#50]
@vvv-school/vvv17-students 

here is the link for the first tutorial on vision

https://classroom.github.com/assignment-invitations/cc84ee46c6114b6bc571c0088d2245d7

**Comment by vicentepedro** [comment]
Can we try this one @vtikha ?
![1228169978606_f](https://cloud.githubusercontent.com/assets/9551355/22594835/1d0d8440-ea25-11e6-9e58-f57f405dd49b.jpg)
