### ISSUE TITLE
Smoke test for assignment

### ISSUE THREAD

**Issue by vtikha** [vvv-school/vvv17#56]
Dear @vvv-school/vvv17-students ,

please be aware that the smoke test has changed. To carry out a proper test, please apply this [**patch**][1] to your local copy of the `test.cpp`.

[1]: https://github.com/vvv-school/assignment_closest-blob/commit/7565d5401fbac48fa50ce92bb5dce26ec12b292f

**Comment by vtikha** [comment]
@vvv-school/vvv17-students 
to simplify things copy and paste the entire test.cpp you can find [here](https://github.com/vvv-school/assignment_closest-blob/blob/master/smoke-test/test.cpp)

**Comment by BarisSerhan** [comment]
:)
<img width="882" alt="screen shot 2017-02-04 at 00 06 56" src="https://cloud.githubusercontent.com/assets/4930060/22612005/3852a408-ea6e-11e6-8086-29d9cf0b1df0.png">

**Comment by pattacini** [comment]
So, what was the final record of yesterday course? 😉

**Comment by BarisSerhan** [comment]
it was 0.9666, not so bad i think

**Comment by bbrito** [comment]
I got 0.97.. something ;)
