### ISSUE TITLE
Script for drawing team leaders for the final assignment

### ISSUE THREAD

**Issue by pattacini** [vvv-school/vvv17#59]
So, it looks like we'll have **lots of candidates as leaders** of the teams we'll form to tackle the final assignment, since many of you @vvv-school/vvv17-teachers are performing really well in this school, and the rest are running up closely (check out the [**ranking**][1]) 🎉 

Therefore, we'll have to pick up those at the top of the final gradebook and possibly also **draw some others**. We could do that at the old manner with names written on small pieces of paper or, even better, with a **script**! 😉 

**Is anybody willing to write that script ?** That would be great! 💻

Requirements:
- We'll run the script on **Ubuntu >= trusty**.
- You can use **bash**, **python**, **ruby**, **lua**...
- You'll have to **`wget` final-gradebook.md** and process it:
    - `wget -O final-gradebook.md https://raw.githubusercontent.com/vvv-school/vvv17/master/final-gradebook.md`
- We would need the script ready and functioning by **Monday morning**.

The script will be pushed to [**vvv17**](https://github.com/vvv-school/vvv17) and used in **future VVV schools**.

[1]: https://vvv-school.github.io/vvv17/final-gradebook.html

**Comment by pattacini** [comment]
Let us know about your commitment to this task.

**Comment by damianomal** [comment]
Hi Ugo, 

here you can find a script which should do the job: 
https://github.com/damianomal/vvv17-get-some-leaders

Hope it helps!

See you tomorrow, 
Damiano

**Comment by pattacini** [comment]
Fantastic @damianomal 😄 

I gave just a try to it and it seems it works nicely in different conditions of the gradebook. In particular, it's not always drawing your username 😉 

Why don't you open a PR and locate this script within the `./scripts` directory of this repository and with default `--file` option equal to `../final-gradebook.md`?
