### ISSUE TITLE
Cannot push to wiki as student

### ISSUE THREAD

**Issue by LuSeKa** [vvv-school/vvv17#62]
Tried to push to the wiki (change in Fun Zone), but push access was denied. Either something is wrong with the permissions or I am doing something wrong...

**Comment by LuSeKa** [comment]
@pattacini

**Comment by pattacini** [comment]
What do you mean with **push**? Through git?
You should just **edit** it. Don't you see the Edit button on the top right of the page?

**Comment by LuSeKa** [comment]
No, no edit button there :(

**Comment by pattacini** [comment]
Damn'
According to this [**post**][1], students should have permission to edit wiki...
I might have misunderstood that. Let me better inquire.

[1]: https://help.github.com/articles/repository-permission-levels-for-an-organization

**Comment by pattacini** [comment]
@LuSeKa done! Now you can edit the wiki.

**Comment by pattacini** [comment]
This post helped out: https://help.github.com/articles/changing-access-permissions-for-wikis
