### ISSUE TITLE
Social Dinner!

### ISSUE THREAD

**Issue by ChiaraBartolozzi** [vvv-school/vvv17#65]
Dear @vvv-school/vvv17-students and @vvv-school/vvv17-teachers 

Please edit this [**page**](https://github.com/vvv-school/vvv17/wiki/Social%20dinner) if you want to attend the social dinner at the very last day.

**Comment by ChiaraBartolozzi** [comment]
cc @vvv-school/vvv17-students @vvv-school/vvv17-teachers

**Comment by pattacini** [comment]
Dear @vvv-school/vvv17-students 
It turned out that you don't have the permission to edit the post, hence we've just made available the same exact table within the wiki.

please edit it here: https://github.com/vvv-school/vvv17/wiki/Social%20Dinner

**Comment by ChiaraBartolozzi** [comment]
Dear @vvv-school/vvv17-students and @vvv-school/vvv17-teachers 

Please remember to update this [page](https://github.com/vvv-school/vvv17/wiki/Social%20dinner) before lunch if you wish to join our final dinner.
