### ISSUE TITLE
Download the iCW dataset for the Deep Learning course 

### ISSUE THREAD

**Issue by GiuliaP** [vvv-school/vvv17#68]
Hi @vvv-school/vvv17-students @vvv-school/vvv17-teachers ,

In order to get ready for the Deep Learning course on Tuesday, you should start downloading a dataset of images that will be used in the hands-on session. Since it is around 500 MB, and you all need to download it, it may be better if you start it in advance.

You can follow these [**instructions**](https://github.com/vvv-school/tutorial_dl-tuning#get-the-data), which include also a simple test that you may want to perform after downloading the dataset, in order to be sure that your system is set up correctly to run `caffe` and fine-tune deep CNNs.

Thank you!
See you on Tuesday :)

Giulia

**Comment by vtikha** [comment]
If for any reason you run into problems with the download, we will also provide the dataset in a USB key on Monday morning.

**Comment by pattacini** [comment]
cc @vvv-school/vvv17-students 

A gentle reminder to download the new dataset for deep learning 😉
