### ISSUE TITLE
Team contest

### ISSUE THREAD

**Issue by pattacini** [vvv-school/vvv17#70]
I'm not in Santa yet, but I guess you're all working on the assignment now, right? 😉 

We've got a news for you. As anticipated a couple of days ago, there'll be a team contest running the last days and tomorrow we're going to create teams, then.

We've just provided some information on the event. [**Check it out**][1] 🎉 

More news to be announced. Stay tuned.

cc @vvv-school/vvv17-students 

[1]: ../wiki/Team-contest

**Comment by vtikha** [comment]
if anyone figured out what @pattacini meant by `being Santa` please let me know 😄

**Comment by pattacini** [comment]
🎅

**Comment by pattacini** [comment]
Hey @vvv-school/vvv17-students 

The gradebooks will be closed at 12:45.
Then, we'll choose the team leaders using @damianomal's [**script**](../blob/master/scripts/draw-team-leaders.py).

**Comment by vtikha** [comment]
Tick Tock ⏳

**Comment by pattacini** [comment]
Teams are now ready!

check it out here: https://github.com/orgs/vvv-school/teams 

@vvv-school/vvv17-teachers @vvv-school/vvv17-students

**Comment by pattacini** [comment]
Let the contest begin!

You can work on the final assignment this evening, tomorrow evening and the whole day of Wednesday!

Good luck!

**Comment by pattacini** [comment]
Let me remind you that each team has its own private repository to work in.

https://github.com/vvv-school/vvv17/wiki/Team%20contest#repositories 

cc @vvv-school/vvv17-students

**Comment by pattacini** [comment]
cc @vvv-school/vvv17-students

**Comment by pattacini** [comment]
Result of drawing:

1. @Arya07 team leader of @vvv-school/vvv17-team-green 
1. @Iaxama team leader of @vvv-school/vvv17-team-orange 
1. @bmagyar team leader of @vvv-school/vvv17-team-blue
