### ISSUE TITLE
Blue team 

### ISSUE THREAD

**Issue by bmagyar** [vvv-school/vvv17#74]
Hello @vvv-school/vvv17-team-blue !

I would like to ask everyone to quickly read through [this](https://github.com/vvv-school/vvv17/wiki/Team-contest) and (while you are crunching matlab tutorials) just think about potential demos or what you'd be interested in doing aligned with what you are good with. 

First thing we should do is to come together and discuss ideas this evening.

**Look me up during the coffee break for your awesome blue wristband!**

**Comment by nolbriker** [comment]
Hey !

Should we create a shared document so that we can write ideas that we can have during the afternoon ?

**Comment by bmagyar** [comment]
Coming up!

**Comment by bmagyar** [comment]
**Trolls keep out**

**Comment by pattacini** [comment]
Please use the private repository instead! 😉 

https://github.com/vvv-school/vvv17-demo-team-blue

**Comment by vicentepedro** [comment]
@vvv-school/vvv17-team-blue, you should use this repository:
https://github.com/vvv-school/vvv17-demo-team-blue
It's a private repo, so, the other teams will not be able to see anything ;)
