### ISSUE TITLE
Material available in the wiki

### ISSUE THREAD

**Issue by pattacini** [vvv-school/vvv17#76]
Andrei Rusu's slides and the material for this afternoon are now available from the wiki.

cc @vvv-school/vvv17-teachers @vvv-school/vvv17-students

**Comment by raffaello-camoriano** [comment]
Dear all,

The solutions of yesterday's machine learning labs are now available in the materials sections and [here](http://lcsl.mit.edu/courses/icub_2017/labs/Machine_Learning_Solutions_iCub_2017.zip).

See the readme file in the provided zip archive.

We hope you enjoyed the labs!

Credits: [George Evengelopoulos](http://web.mit.edu/gevang/www/)
Ciao!

**Comment by pattacini** [comment]
Thanks @Ommac
