### ISSUE TITLE
Join the team and send the presentation

### ISSUE THREAD

**Issue by pattacini** [vvv-school/vvv17#8]
@AlexisBillier and @damianomal
Please, accept the invitation to join the team that you should have received in your mail box.

@alexarossi @anatanevska @bmagyar @ipa-bfb @EgorLakomkin @BrutusTT @kompky @LuSeKa @pi-q 
Please, send us the one-page pdf presentation.

- [x] @AlexisBillier to join the team
- [x] @damianomal to join the team
- [x] @ipa-bfb to send the presentation
- [x] @BrutusTT to send the presentation
- [x] @kompky to send the presentation

**Comment by pi-q** [comment]
Hi Ugo,

Here is my presentation. Let me know if you need anything more.

Cheers,

Marie

**Comment by pattacini** [comment]
Thanks @pi-q, just uploaded!

**Comment by alexarossi** [comment]
Ciao Ugo,

Attached you can find my presentation. Sorry for the delay.

Cheers,
Alessandra

**Comment by bmagyar** [comment]
Hiya, 
Mine is on #9 
Cheers,
Bence

**Comment by pattacini** [comment]
Ciao @alexarossi 

Didn't receive your slide yet. Do you mind drop me an ✉️ at this [**address**][1] with the slide attached?

See you.

[1]: mailto:vvv-admin@iit.it

**Comment by pattacini** [comment]
Reminder

- [ ] @AlexisBillier to join the team
- [ ] @damianomal to join the team
- [ ] @ipa-bfb to send the presentation
- [ ] @BrutusTT to send the presentation
- [ ] @kompky to sent the presentation

**Comment by pattacini** [comment]
We're all done, thanks!
