### ISSUE TITLE
Cannot open evening talk by Danica Kragic: "Acting and interacting in a real world "

### ISSUE THREAD

**Issue by bbrito** [vvv-school/vvv17#83]
Do you know where are these slides?

**Comment by pattacini** [comment]
Hi @ipa-bfb 

Apparently, they've been removed. Let me ask @lornat75.

Stay tuned.
Cheers 😃

**Comment by pattacini** [comment]
Hi @ipa-bfb 
The problem should be solved now.
Cheers
