### ISSUE TITLE
iCub_SIM component problem

### ISSUE THREAD

**Issue by accateo** [vvv-school/vvv17#84]
Hi,

I don't know if this is the right place to ask this question. 

I'm following your YARP tutorial and I'm at the point that I have to run `iCub_SIM`. I run it, and all it's ok. 

When I run `yarpmotorgui`, a popup window appears, asking me what component of the iCub control I want to select. I select all the components (I have also tried to select only some), I click on OK, but different windows show up reporting:
```
Error while opening device /icub/head
```

The same thing happens with `yarpmanager`.

Why does this happen?
Thanks

**Comment by vtikha** [comment]
Hi @accateo The only thing you need to do here is write `icubSim` instead of `icub` in the popup window when you select which component you need. I would suggest to use the [Q&A](https://github.com/robotology/QA) section for any questions you may have.

**Comment by pattacini** [comment]
Hi @accateo ,

Next time, please use our [**Q&A**][1] system instead 😉 

[1]: https://github.com/robotology/QA

**Comment by accateo** [comment]
Thanks! It works! Sorry for the wrong place.
